### ISSUE TITLE
sample_tabulator

### ISSUE THREAD

**Issue by Arnob013** [lguillaud/osd_transform_vis#9] opened 2023-08-30 15:37 UTC
the sampleVizs has this sample tabulator. why the dropdown option does not show as intended. attaching the picture below. I am using OSD-2.8.0 ; As you can see the male and female comes at the bottom of the page. 
![image](https://github.com/lguillaud/osd_transform_vis/assets/84742024/2d79b935-f20c-4123-aced-13f6a3dfb5be)

**Comment by lguillaud** [comment] 2023-09-20 11:55
Hello,
This is fixed, was an issue with css.
Lionel

**Comment by Arnob013** [comment] 2024-02-22 10:49
Hi I have tried this. it works for the first time. then after refreshing the page the problem occurs again. what solution do you suggest? also what are the CSS change you applied? there is only the tabulator CSS that you are referring to in your sample-tabulator.

**Comment by Arnob013** [comment] 2024-02-22 10:56
Thanks a lot for the previous response. I am looking forward to a solution from you :)

**Comment by lguillaud** [comment] 2024-02-22 11:07
Hello,
Could please give me more details to reproduce the issue ? I get the right behaviour on my side.
- Is the issue happening in the visualize tab or from within a dashboard ?
- How do you refresh: F5 in the browser or time range update ?
- Browser used
- any other things you can think that can help

The change I have applied is to add a CSS function in the JS window.

**Comment by Arnob013** [comment] 2024-02-22 11:11
1. the issue is happening on both visualize and dashboard. 
2. refresh with F5
3. edge, chrome both has same issue
4. I have a code of mine, but the basic structure is the same with your code. only the data I am fetching from an opensearch index.

also can you provide the CSS function that you applied in pre ndjson. It is very difficult for me to read the ndjson file.

**Comment by Arnob013** [comment] 2024-02-22 11:22
I can provide the sample skeleton of the JS code and template if that can help. the data fetch part wont work though as I can not give you the data index

**Comment by lguillaud** [comment] 2024-02-22 12:44
You can get the code by import the visualizations examples: see https://github.com/lguillaud/osd_transform_vis?tab=readme-ov-file#visualisation-samples

**How to load ndjson files** ? Open OpenSearch Dashboards > Stack Management > Saved Objects > Import > Select ndjson file to import > Click Import

**How to open the samples once loaded** ? Open OpenSearch Dashboards > Visualize > Click on the visualization you just imported

Below the code used:
```
({
  css: function() {  
      const css_list = ["https://cdn.jsdelivr.net/npm/tabulator-tables@5.5.0/dist/css/tabulator.min.css"];  
      for (let css_file of css_list) {
          const links = document.head.querySelectorAll("link");

          for(let l in links)
            if(links[l].href == css_file) return;
            const link = document.createElement('link');
            link.rel = "stylesheet";
            link.href = css_file;
            document.head.appendChild(link);
        } 
},
  after_render: function() { ......
```

**Comment by Arnob013** [comment] 2024-04-12 08:08
the issue is back. dropdown not working 

![Screenshot 2024-04-12 110127](https://github.com/lguillaud/osd_transform_vis/assets/84742024/5d085b76-0e0b-4eb0-980a-4399239c5e8a)

**Comment by lguillaud** [comment] 2024-04-12 08:14
Which version are you using?

**Comment by Arnob013** [comment] 2024-04-12 08:17
i am using version 2.8.0 for opensearch

**Comment by lguillaud** [comment] 2024-04-15 08:09
Just tested in a fresh 2.8.0 env, and it's working fine.
Are you using the CSS function ? https://github.com/lguillaud/osd_transform_vis/issues/9#issuecomment-1959383542

**Comment by Arnob013** [comment] 2024-04-15 10:04
I am using the css function. 
 css: function () {
    const css_list = ["https://cdn.jsdelivr.net/npm/tabulator-tables@5.5.0/dist/css/tabulator.min.css"];
    for (let css_file of css_list) {
      const links = document.head.querySelectorAll("link");

      // Already been injected
      for (let l in links)
        if (links[l].href == css_file) return;
      const link = document.createElement('link');
      link.href = css_file;
      document.head.appendChild(link);
    }
  }

still not working

**Comment by lguillaud** [comment] 2024-04-15 12:20
Did not notice it was the same version as the one for which you created the issue.
No modifications at all have been made for 2.8.0 plugin version and also the tabulator example.
Sorry but I cannot reproduce the issue. :-(

**Comment by lguillaud** [comment] 2024-05-02 14:01
Closing issue but feel free ro re-open it if you have any new information.

**Closed as completed by lguillaud** 2024-05-02 14:01 UTC
